# Generated by Django 5.2 on 2025-04-11 15:21

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('description', models.CharField(max_length=100, verbose_name='توضیحات')),
                ('content', ckeditor.fields.RichTextField(verbose_name='متن')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': ' بلاگ',
                'verbose_name_plural': 'بلاگ ها  ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('sluf', models.SlugField(verbose_name='عنوان لاتین')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='تاریخ انتشار ')),
            ],
            options={
                'verbose_name': ' دسته بندی',
                'verbose_name_plural': ' دسته بندی ها  ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام کاربر')),
                ('email', models.EmailField(max_length=254, verbose_name='آدرس ایمیل ')),
                ('message', models.TextField(verbose_name='متن کامنت')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': ' کامنت ',
                'verbose_name_plural': '  کامنت ها   ',
                'managed': True,
            },
        ),
    ]
