# Generated by Django 5.2 on 2025-04-21 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_medicalmajor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.medicalmajor', verbose_name='تخصص'),
        ),
    ]
