# Generated by Django 5.2 on 2025-04-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ نوبت')),
                ('time', models.TimeField(verbose_name='ساعت نوبت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('rejected', 'رد شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت\u200cها',
            },
        ),
    ]
